
#puerto de producción
server.port=9192
#puerto desarrollo
#server.port=9091
spring.application.name=RMPAYCalendarservice
#spring.mvc.validation.fail-on-errors=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración SSL con mkcert
server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1


# DATASOURCE (SQL SERVER)
# =========================
# DB1 - POSDPS (principal)
# =========================
spring.datasource.db1.jdbc-url=jdbc:sqlserver://localhost\\CSE;database=POSDPS;TrustServerCertificate=True
spring.datasource.db1.username=sa
spring.datasource.db1.password=euchp1
spring.datasource.db1.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =========================
# DB2 - RMShopper
# =========================
spring.datasource.db2.jdbc-url=jdbc:sqlserver://localhost\\CSE;database=ShopifyServiceDB;TrustServerCertificate=True
spring.datasource.db2.username=sa
spring.datasource.db2.password=euchp1
spring.datasource.db2.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost;database=RMShopper;TrustServerCertificate=True
#spring.datasource.url=jdbc:sqlserver://192.168.100.76\\CSE;database=RMShopper;TrustServerCertificate=True
#spring.datasource.url=jdbc:sqlserver://localhost\\CSE;database=POSDPS;TrustServerCertificate=True
#spring.datasource.username=sa
#spring.datasource.password=euchp1
#spring.datasource.username=COLOMBIA2
#spring.datasource.password=fzHbP9Z2eb9-Y?<N

# =========================
# RABBIT
# =========================
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=6
# =========================
# SHOPPIFY
# =========================
shopify.url=${SHOPIFY_URL:https://retailmanager.myshopify.com/admin/api/2026-04/graphql.json}

shopify.urlAccesToken=${SHOPIFY_URL_ACCESS_TOKEN:https://retailmanager.myshopify.com/admin/oauth/access_token}

shopify.client_secret=${SHOPIFY_CLIENT_SECRET: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}

shopify.client_id=${SHOPIFY_CLIENT_ID:84a80e678cd7f315fd66d8f2cac5825f}

shopify.grant_type=${SHOPIFY_GRANT_TYPE:client_credentials}

pos.base-url=${POS_BASE_URL:http://localhost:8180}

#JPA

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=debug
# Table names physically
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#--- 
spring.config.activate.on-profile=docker
spring.datasource.url=${SQL_URL}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=${hibernate_ddl_auto}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
